
import { cn } from "@/utils/styles";

export function Spinner({
  className,
  isLoading = true,
  variant = "default",
}: {
  className?: string;
  isLoading?: boolean;
  variant?: "default" | "primary";
}) {
  if (!isLoading) return null;

  const variantClasses = {
    default: "border-foreground/20 border-t-muted-foreground",
    primary: "border-secondary/40 border-t-secondary",
  };

  return (
    <div
      className={cn(
        "animate-spin rounded-full w-4 h-4 border-[0.15em]",
        variantClasses[variant],
        className,
      )}
      role="status"
      aria-label="Loading"
    />
  );
}

///////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by the Next.js compiler. Do not edit this file directly.
// Instead, edit the source file located at components/ui/spinner.tsx
//////////////////////////////////////////////////////////////////////////////
// import { Loader2Icon } from 'lucide-react'

// import { cn } from '@/lib/utils'

// function Spinner({ className, ...props }: React.ComponentProps<'svg'>) {
//   return (
//     <Loader2Icon
//       role="status"
//       aria-label="Loading"
//       className={cn('size-4 animate-spin', className)}
//       {...props}
//     />
//   )
// }

// export { Spinner }
